select * from TBL_USER;
select * from TBL_BOARD;
select * from TBL_COMMENT;

select to_char(CDATETIME, 'YYYY-MM-DD HH24:MI;SS') FROM TBL_USER;

-- INNER JOIN

SELECT BOARDNO, NAME
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID;

-- 각 유저가 작성한 게시글 수

SELECT *
FROM TBL_USER U
LEFT JOIN TBL_BOARD B ON B.USERID = U.USERID; ------ NULL도 1개로 COUNT됨


-- 각 유저가 작성한 게시글 수, USERID, NAME
SELECT U.USERID, NAME, COUNT(BOARDNO)AS CNT
FROM TBL_USER U
LEFT JOIN TBL_BOARD B ON B.USERID = U.USERID ------ NULL도 1개로 COUNT됨
GROUP BY U.USERID, NAME;

SELECT B.USERID, NAME, COUNT(BOARDNO) CNT
FROM TBL_BOARD B
RIGHT JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.USERID, NAME;

-- 각 유저가 작성한 댓글의 수 : 아이디, 이름, 댓글수
SELECT U.USERID, NAME, COUNT(COMMENTNO) CNT
FROM TBL_USER U
LEFT JOIN TBL_COMMENT C ON U.USERID = C.USERID
GROUP BY U.USERID, NAME;


-- TBL_USER, TBL_BOARD, TBL_COMMENT
--1. 아이디에 USER가 들어가는 사람이 작성한 게시글의 수
SELECT COUNT(*)
FROM TBL_BOARD
WHERE USERID LIKE '%user%';


--2. USER의 핸드폰 번호 가운데를 *로 처리(가운데 4자리는 고정)
SELECT SUBSTR(PHONE,1,INSTR(PHONE, '-'))||'****'||SUBSTR(PHONE,INSTR(PHONE, '-')+5,LENGTH(PHONE)) AS PHONE
FROM TBL_USER;

SELECT REPLACE(PHONE,SUBSTR(PHONE,5,4), '****') --- 뒷자리가 가운데와 동일하면 주의해야한다
FROM TBL_USER;
-- INSTR(PHONE, '-') : '글자'의 위치 확인


--3. 게시글에 좋아요 개수가 가장 큰 게시글을 작성한 사람의 아이디, 이름 좋아요 개수 출력
SELECT B.USERID, NAME, CNT 
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID 
WHERE FAVORITE = (
    SELECT MAX(FAVORITE)AS CNT 
    FROM TBL_BOARD B
);


--4. 게시글 번호, 제목, 내용, 작성자 닉네임, 뎃글 수(없으면 0)출력
SELECT B.BOARDNO, TITLE, B.CONTENTS, NICKNAME, COUNT(COMMENTNO)AS 댓글수 
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, TITLE, B.CONTENTS, NICKNAME;


--5. 조회수가 가장 큰 게시글의 게시글 번호, 제목 , 작성자 닉네임 출력
SELECT B.BOARDNO, TITLE, NICKNAME, CNT
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
WHERE CNT = (
    SELECT MAX(CNT) AS CNT 
    FROM TBL_BOARD B
);







