-- UNION

SELECT
    STU_NO,
    STU_NAME,
    STU_DEPT
FROM STUDENT
WHERE STU_HEIGHT >=170

UNION -- UNION은 중복은 1개로 출력해준다.

SELECT
    STU_NO,
    STU_NAME,
    STU_DEPT
FROM STUDENT
WHERE STU_WEIGHT >=50;
    
    
SELECT
    STU_NO,
    STU_NAME,
    STU_DEPT
FROM STUDENT
WHERE STU_HEIGHT >=170

UNION ALL -- UNION ALL은 중복된 경우 모두 출력해준다.

SELECT
    STU_NO,
    STU_NAME,
    STU_DEPT
FROM STUDENT
WHERE STU_WEIGHT >=50;    

SELECT COUNT(*) FROM STUDENT
UNION
SELECT STU_NAME FROM STUDENT; -- 타입이 달라서 에러

SELECT STU_NAME AS TEMP FROM STUDENT
UNION
SELECT STU_DEPT FROM STUDENT;

SELECT STU_NAME AS TEMP FROM STUDENT
UNION
SELECT STU_NAME, STU_DEPT FROM STUDENT; -- 컬럼의 개수가 달라 에러


SELECT S.STU_NAME, AVG(ENR_GRADE)AS 평균, 1 AS ORDERKEY
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME
UNION
SELECT '전체 평균', ROUND(AVG(ENR_GRADE),1), 2 AS ORDERKEY
FROM ENROL
ORDER BY ORDERKEY, 평균 DESC;

SELECT STU_NAME, 평균 ------ 위에서 ORDERKY없이 출력하는 법
FROM (
    SELECT S.STU_NAME, AVG(ENR_GRADE)AS 평균, 1 AS ORDERKEY
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
    GROUP BY STU_NAME

    UNION

    SELECT '전체 평균', ROUND(AVG(ENR_GRADE),1), 2 AS ORDERKEY
    FROM ENROL
    ORDER BY ORDERKEY, 평균 DESC
);

SELECT DNAME 부서명, ROUND(AVG(SAL)) AS 평균급여
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME
UNION
SELECT '전체평균', ROUND(AVG(SAL))
FROM EMP;


SELECT ROWNUM, S.*  -- 새로운 번호를 생성하며 테이블을 만든다.
FROM STUDENT S
WHERE ROWNUM <=5;

SELECT ROWNUM, S.*
FROM STUDENT S
WHERE ROWNUM =2; --- DATA생성하지 않음

SELECT *
FROM (
    SELECT ROWNUM RN, S.*
    FROM STUDENT S
)S;
    
SELECT ROWNUM, S.*
FROM STUDENT S
ORDER BY STU_HEIGHT DESC; ---- 맨마지막에 ORDER를 하니 ROWNUM이 섞인다.

SELECT ROWNUM , S.*
FROM(
    SELECT *
    FROM STUDENT S
    WHERE STU_HEIGHT IS NOT NULL
    ORDER BY STU_HEIGHT DESC   -- NULL은 내림차순으로하면 처음에 위치함
)S
WHERE ROWNUM <=5;

-- 평균급여가 2번째로 큰 부서의 부서면, 평균급여 출력

SELECT DNAME,ROUND(AVG(SAL)) AS 평균급여
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME
ORDER BY 평균급여 DESC;

SELECT DNAME, 평균급여
FROM(
    SELECT ROWNUM RN, S.*
    FROM(
        SELECT DNAME,ROUND(AVG(SAL)) AS 평균급여
        FROM EMP E
        INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
        GROUP BY DNAME
        ORDER BY 평균급여 DESC
    )S
)S
WHERE RN = 2;







   