-- 그룹함수2
-- SUB, AVG, MAX, MIN COUNT

SELECT NAME, SUM(PAY)    -- 그룹 함수값은 하나인데 컬럼값은 여러개로 같이 쓰면 ERROR
FROM PROFESSOR;

SELECT POSITION, SUM(PAY)
FROM PROFESSOR
GROUP BY POSITION;    -- 교수포지션별로 그룹을 만드므로 서로 대응 값들을 갖어 문제 없다.

SELECT * FROM STU;

SELECT GRADE, AVG(WEIGHT)
FROM STU
GROUP BY GRADE;

SELECT GRADE, MAX(WEIGHT)
FROM STU
GROUP BY GRADE;

SELECT * FROM STUDENT;

SELECT COUNT(*)  --- 전체 레코드 수
FROM STUDENT;

SELECT COUNT(BONUS) -- BONUS가 NULL이 아닌 레코드의 수
FROM PROFESSOR;


SELECT STU_DEPT, COUNT(*) -- 학과별 학생 수가 4명 이상인 학과
FROM STUDENT
GROUP BY STU_DEPT  -- WHERE문은 GROUP문 앞에 와야 한다. COUNT는 GROUP뒤어 올 수 없다.
HAVING COUNT(*) >=4; -- HAVING문으로 처리한다.

SELECT STU_DEPT, COUNT(*) --학과에서 남자가 있는 학과 학생수
FROM STUDENT
WHERE STU_GENDER = 'M'
GROUP BY STU_DEPT;


SELECT STU_DEPT, COUNT(*) -- 학과에서 남자가 2명이상인 학과 학생수
FROM STUDENT
WHERE STU_GENDER = 'M'
GROUP BY STU_DEPT
HAVING COUNT(*) >=2;
