-- STUDENT TABLE기준
-- 모든 레코드 출력
-- STUDENT TABLE에서 이름, 학과, 학년 출력
-- 컴퓨터정보과 학생만 출력
-- 기계과 이면서 남자인 학생들만 출력
-- 몸무게 50~70 사이의 학생들 출력

SELECT *
FROM STUDENT;

SELECT STU_NAME, STU_DEPT, STU_GRADE
FROM STUDENT;

SELECT *
FROM STUDENT
WHERE STU_DEPT = '컴퓨터정보';

SELECT *
FROM STUDENT
WHERE STU_DEPT = '기계' AND STU_GENDER = 'M';

SELECT *
FROM STUDENT
--WHERE STU_WEIGHT >= 50 AND STU_WEIGHT <= 70;
WHERE STU_WEIGHT BETWEEN 50 AND 70;
