-- 숫자함수, 문자함수, 날짜함수

-- ROUND
SELECT 'TEST' FROM DUAL;  --- TEST PRINT
SELECT ROUND(123.4567, 2) FROM DUAL;  -- 2자리까지 반올림으로 계산

SELECT ROUND(AVG(STU_HEIGHT), 2) AS 평균키
FROM STUDENT
WHERE STU_DEPT = '기계';

-- TRUNC : 소수점을 특정 이하에서 버림(올림, 내림 없음)
SELECT TRUNC(123.4567, 2) -- 123.45출력
FROM DUAL;

SELECT TRUNC(AVG(STU_HEIGHT), 5) AS 평균키
FROM STUDENT
WHERE STU_DEPT = '기계'; -- 165.33333 출력

-- CEIL : 무조건 숫자를 올림해서 가장 가까운 정수로 반환
SELECT CEIL(123.456) -- 124출력
FROM DUAL;

-- FLOOR - 무조건 숫자를 내려서 가장 가까운 정수로 반환
SELECT FLOOR(123.456) -- 123출력
FROM DUAL;

-- 그룹함수

SELECT MAX(STU_HEIGHT)AS MAX_HEIGHT
FROM STUDENT;

SELECT STU_NAME AS 이름 -- AS생략 가능
FROM STUDENT;

SELECT AVG(STU_HEIGHT) AS "평균 키"
FROM STUDENT;

SELECT SUM(STU_HEIGHT)
FROM STUDENT;

SELECT * FROM STUDENT;

SELECT AVG(STU_HEIGHT)
FROM STUDENT
WHERE STU_DEPT = '기계';

SELECT * FROM PROFESSOR;

SELECT SUM(PAY)
FROM PROFESSOR
WHERE POSITION = '정교수';

-- MOD : 나머지 반환
SELECT MOD(10,3) -- 10/3의 나머지 1출력
FROM DUAL;

-- SIGN : 숫자의 부호를 변환하는 함수. 양수면 1, 음수면 -1, 0이면 0
SELECT SIGN(-2)   -- -1출력
FROM DUAL;

-- ABS : 절대값
SELECT ABS(-10)
FROM DUAL;

-- POWER : 거듭제곱
SELECT POWER(2, 3) -- 2의 3제곱 = 8
FROM DUAL;
