-- STUDENT TABLE에서 각 학과의 가장 키가 큰 사람의 학번 이름 키 출력

SELECT * FROM STUDENT;

SELECT STU_DEPT, MAX(STU_HEIGHT)MAX_HEIGHT
FROM STUDENT
GROUP BY STU_DEPT;

SELECT * --S.STU_DEPT, STU_NO, STU_NAME, S.STU_HEIGHT
FROM STUDENT S
INNER JOIN (
    SELECT STU_DEPT, MAX(STU_HEIGHT) AS MAX_HEIGHT
    FROM STUDENT
    GROUP BY STU_DEPT
)T ON S.STU_DEPT = T.STU_DEPT AND S.STU_HEIGHT = T.MAX_HEIGHT;


-- 각 직급별 가장 많은 급여를 받는 교수의 이름, 급여 출력
SELECT * FROM PROFESSOR;

-- 직급별 최대 급여
SELECT POSITION,MAX(PAY)
FROM PROFESSOR
GROUP BY POSITION;

SELECT *
FROM PROFESSOR P
INNER JOIN (
    SELECT POSITION, MAX(PAY) AS MAX_PAY 
    FROM PROFESSOR
    GROUP BY POSITION
) T ON P.POSITION = T.POSITION AND P.PAY = T.MAX_PAY;


-- 본인 부서의 평균 급여보다 높은 급여를 받는 사원의 사번, 이름 급여 출력
SELECT * FROM EMP;

SELECT AVG(SAL)
FROM EMP
GROUP BY DEPTNO;

SELECT EMPNO, ENAME, SAL, ROUND(AVG_SAL)
FROM EMP E
GROUP BY DEPTNO
INNER JOIN (
    SELECT DEPTNO, AVG(SAL) AS AVG_SAL
    FROM EMP
    GROUP BY DEPTNO
) T ON E.DEPTNO = T.DEPTNO AND E.SAL > T.AVG_SAL;

