-- SELECT, UPDATE, INSERT, DELETE : 오라클에서 엘리먼트 대소문자 구분은 딱히 하지 않는다.
-- 데이터는 대소문자구분 해야 한다.

SELECT *
FROM STUDENT
WHERE STU_GENDER = 'F' AND STU_DEPT = '전기전자';

SELECT STU_DEPT, ROUND(AVG(STU_DEPT))
FROM STUDENT
GROUP BY STU_DEPT;

SELECT * FROM PROFESSOR
WHERE LENGTH(ID) >= 6;

UPDATE PROFEESOR
SET
    PAY = PAY + 50
WHERE LENGTH(ID) >= 6;

SELECT * FROM PROFESSOR;

INSERT INTO STUDENT(STU_NO, STU_NAME, STU_DEPT)
VALUES('12341234', '홍길동', '기계');

INSERT INTO STUDENT  -- 모든 값을 넣게 되면 열변수들 생략 가능
VALUES('12345678', '김철수', '전기전자', 1, 'A', 'M', 175, NULL);
