-- 연습문제

--1. '컴퓨터정보' 학과에 속한 학생들의 학번, 이름, 평균시험점수를 출력하시오
--(STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;

SELECT STU_DEPT, S.STU_NO, STU_NAME, AVG(ENR_GRADE)평균점수
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE STU_DEPT = '컴퓨터정보'
GROUP BY STU_DEPT, S.STU_NO, STU_NAME;

SELECT S.STU_NO, STU_NAME, AVG(ENR_GRADE) AS AVG_SCORE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
WHERE STU_DEPT = '컴퓨터정보'
GROUP BY S.STU_NO, STU_NAME;

--2. '강종영' 교수의 과목 시험을 본 학생의 학번, 이름, 점수, 과목명을 출력하시오.
--(STUDENT, ENROL, SUBJECT)
SELECT * FROM SUBJECT;

SELECT SUB.SUB_PROF, S.STU_NO, STU_NAME, ENR_GRADE, SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB.SUB_PROF = '강종영';


SELECT S.STU_NO, STU_NAME, ENR_GRADE, SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
WHERE SUB.SUB_PROF ='강종영';

--3. 학생들의 이름, 시험을 본 개수를 출력하시오. 
--- 시험을 안본 사람은 출력을 안하거나 0으로 출력하거나 상관없음.
--(STUDENT, ENROL)
SELECT STU_NAME,COUNT(DECODE(ENR_GRADE,NULL,NULL)) 시험않본수,  
                COUNT(DECODE(ENR_GRADE,ENR_GRADE,ENR_GRADE)) 시험본수
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO
GROUP BY STU_NAME;

SELECT STU_NAME, COUNT(*) 시험수
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_NAME;

--4. 모든 학생들의 시험 평균 점수보다 높은 평균점수를 가지는 학생들의 학번, 이름, 평균점수를 출력하시오.
--(STUDENT, ENROL)
SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;


SELECT S.STU_NO, STU_NAME, ROUND (AVG(ENR_GRADE),2) 평균점수
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
--WHERE AVG(ENR_GRADE)
HAVING AVG(ENR_GRADE) > (               -- WHERE는 GROUP문 앞에 와야 한다.
    SELECT AVG(ENR_GRADE) --- 전체 점수 평균값
    FROM STUDENT S
    INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
)
GROUP BY S.STU_NO, STU_NAME;

--???




--5. 사원번호, 이름, 급여 등급, 사수(MANAGER)이름을 출력하시오.
--(EMP, SALGRADE)
SELECT * FROM EMP;
SELECT * FROM SALGRADE;
SELECT * FROM DEPT;

SELECT E1.EMPNO, E1.ENAME 부사수, GRADE, E2.ENAME 사수
FROM EMP E1
INNER JOIN DEPT D ON E1.DEPTNO = D.DEPTNO   --- 불필요
INNER JOIN SALGRADE S ON SAL BETWEEN S.LOSAL AND S.HISAL
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;
--WHERE E1.ENAME = 'SCOTT'; SCOTT의 자료

SELECT E1.EMPNO, E1.ENAME, GRADE, E2.ENAME AS MGR_NAME
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO
INNER JOIN SALGRADE S ON E1.SAL BETWEEN S.LOSAL AND S.HISAL;

--6. 부서별 급여의 평균 등급을 출력하시오. - 부서명, 급여 평균 등급 출력
--(EMP, SALGRADE, DEPT)
SELECT DNAME, ROUND(AVG(GRADE))
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S ON SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY DNAME;

SELECT DNAME, ROUND(AVG(GRADE), 1)
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY DNAME;

--7. 인문대학에 속한 교수의 이름을 모두 출력하시오.
--(PROFESSOR, DEPARTMENT)
SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

SELECT D3.DNAME, P.NAME
FROM DEPARTMENT D1
INNER JOIN DEPARTMENT D2 ON D1.DEPTNO = D2.PART 
INNER JOIN DEPARTMENT D3 ON D2.DEPTNO = D3.PART
INNER JOIN PROFESSOR P ON D3.DEPTNO = P.DEPTNO
WHERE D1.DEPTNO = 20;

SELECT NAME, D1.DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D1 ON P.DEPTNO = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
INNER JOIN DEPARTMENT D3 ON D2.PART = D3.DEPTNO
WHERE D3.DNAME = '인문대학';

