-- 서브 쿼리

SELECT MAX(PAY)
FROM PROFESSOR;

-- 급여 제일 많이 받는 사람
SELECT *
FROM PROFESSOR
WHERE PAY = (
        SELECT MAX(PAY)
        FROM PROFESSOR
);

-- 급여 제일 많이 받는 사람과 제일 적게 받는 사람
SELECT *
FROM PROFESSOR
WHERE PAY = (
        SELECT MAX(PAY)
        FROM PROFESSOR
) OR PAY = (
        SELECT MIN(PAY)
        FROM PROFESSOR
);


SELECT * 
FROM PROFESSOR
WHERE DEPTNO = (
    SELECT DEPTNO
    FROM DEPARTMENT
    WHERE DNAME = '컴퓨터공학과'
);

SELECT DEPTNO
FROM DEPARTMENT
WHERE DNAME = '컴퓨터공학과';

SELECT DEPTNO 
FROM PROFESSOR
WHERE DEPTNO IN (
    SELECT DEPTNO
    FROM DEPARTMENT
    WHERE DNAME IN ('컴퓨터공학과', '멀티미디어공학과')
);

SELECT DEPTNO
FROM DEPARTMENT
WHERE DNAME IN ('컴퓨터공학과', '멀티미디어공학과');

SELECT *
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO;
--WHERE D.DNAME IN ('컴퓨터공학과', '멀티미디어공학과');

SELECT * FROM PROFESSOR;
