-- JOIN : 관계형 DB 핵심, 방법 INNER JOIN
-- 오라클 조인(좀 배타적 로직), ANSI 조인(MAJORITY)-수업방향
-- 2개 이상의 테이블을 연결해서 데이터를 도출하는 방법
-- INNER JOIN 테이블명 ON 열이름 조건식(BETWEEN, =, <, >)

SELECT * FROM STUDENT; -- 기본정보 학번은 PK
SELECT * FROM ENROL; -- 학번, 성적정보 -- 학번은 STUDENT의 PK인데, ENROL에서 이를 참조 --> FK(FOREIN KEY)
SELECT * FROM SUBJECT; -- 과목번호는 PK -- 과목번호는 SUBJECT의PK인데, ENROL에서 이를 참조 --> FK(FOREIN KEY)

SELECT S.STU_NO, STU_NAME, STU_DEPT, ENR_GRADE -- 중복된 경우 어느 테이블인지 구분해야함
FROM STUDENT S -- 별칭
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;
         

SELECT S.*, ENR_GRADE ------ STUDENT의 모든 열 출력, ENROL의 ENR_GRADE출력
FROM STUDENT S -- 별칭
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO;

-- 학번, 이름, 학과, 평균점수 출력
SELECT S.STU_NO, STU_NAME, STU_DEPT, AVG(ENR_GRADE)
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NO, STU_NAME, STU_DEPT;


SELECT * FROM PROFESSOR;
SELECT * FROM DEPARTMENT;

-- 교수번호, 교수이름, 학과명 출력
SELECT PROFNO, NAME, DNAME
FROM PROFESSOR P
INNER JOIN DEPARTMENT D ON P.DEPTNO = D.DEPTNO; 

SELECT * FROM EMP;
SELECT * FROM DEPT;

-- 사번, 이름, 직급(JOB), 부서명(DEPNO) 출력
SELECT EMPNO, ENAME, JOB, DNAME
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

-- 학번, 이름, 학과, 시험점수 출력 후, 과목명

SELECT * FROM STUDENT; -- STU_NO
SELECT * FROM ENROL; -- STU_NO, SUB_NO
SELECT * FROM SUBJECT; -- SUB_NO

SELECT S.STU_NO, STU_NAME, ENR_GRADE, SUB_NAME
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON E.SUB_NO = SUB.SUB_NO;

--

SELECT * FROM EMP;
SELECT * FROM SALGRADE;  -- 급여의 등급

SELECT EMPNO, ENAME, SAL, GRADE
FROM EMP E
INNER JOIN SALGRADE S ON E.SAL BETWEEN S.LOSAL AND S.HISAL;

-- SELF JOIN
SELECT E1.ENAME 직원이름, E2.ENAME 매니저이름
FROM EMP E1
INNER JOIN EMP E2 ON E1.MGR = E2.EMPNO;
--WHERE E1.ENAME = 'ALLEN';


-- 공과대학내 모든 학과명 출력
SELECT * FROM DEPARTMENT; 

SELECT D3.DNAME
FROM DEPARTMENT D1 
INNER JOIN DEPARTMENT D2 ON D1.DEPTNO = D2.PART -- DEPTNO를 PART와 조인 : 공과대학에 속한 공학학부 출력
INNER JOIN DEPARTMENT D3 ON D2.DEPTNO = D3.PART -- DEPTNO를 PART와 조인 : 공학학부에 속한 학과 출력
WHERE D1.DEPTNO = '10'; -- WHERE D1.DNAME = '공과대학'





