
SELECT *
FROM PROFESSOR
WHERE BONUS IS NULL;   -- IS NOT NULL
-- IN, LIKE, BETWEEN, IS NULL, IS NOT NULL

-- 서브쿼리 (쿼리안에 또 다른 쿼리)

SELECT MAX(STU_HEIGHT)  -- 188인데 누구인지는 모름
FROM STUDENT;

SELECT STU_NAME, STU_HEIGHT                -- 키값을 하드코딩해야함  
FROM STUDENT
-- WHERE STU_HEIGHT = 188;
WHERE STU_HEIGHT = (
    SELECT MAX(STU_HEIGHT)
    FROM STUDENT
);

-- 학생들의 전체 평균보다 큰 키를 가진 학생 출력

SELECT STU_HEIGHT FROM STUDENT;

SELECT STU_NAME, STU_HEIGH
FROM STUDENT
WHERE STU_HEIGHT > (
    SELECT AVG(STU_HEIGHT)
    FROM STUDENT
);



