SELECT * FROM TBL_USER;
SELECT * FROM TBL_BOARD;
SELECT * FROM TBL_COMMENT;



SELECT B.USERID, NICKNAME, COUNT(*)
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
GROUP BY B.USERID, NICKNAME;

SELECT NICKNAME, TITLE
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID;

-- 각 게시글의 제목, 댓글 개수
-- 게시글에 댓글이 없으면 개수를 0으로 출력

SELECT B.BOARDNO, COUNT(*)
FROM TBL_BOARD B
INNER JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO;

SELECT B.TITLE, NVL(COUNT(COMMENTNO),0) AS 댓글수
FROM TBL_BOARD B
LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
GROUP BY B.BOARDNO, B.TITLE;

-- 게시글 번호, 게시글 제목, 내용, 작성일, 작성자 닉네임, 댓글개수(없으면 0)

SELECT B.BOARDNO, TITLE, B.CONTENTS, B.CDATETIME, NICKNAME, 댓글수
FROM TBL_BOARD B
INNER JOIN TBL_USER U ON B.USERID = U.USERID
INNER JOIN (
    SELECT B.BOARDNO, COUNT(COMMENTNO) AS 댓글수
    FROM TBL_BOARD B
    LEFT JOIN TBL_COMMENT C ON B.BOARDNO = C.BOARDNO
    GROUP BY B.BOARDNO
) T ON B.BOARDNO = T.BOARDNO;


-- CASE ~ WHEN
-- PROFESSOR
-- PROFESSOR TABLE에서 400이상급여이면 A, 300~400사이면 B, 나머지는 C로 출력
-- 교수이름, 급여등급

SELECT
    NAME,
    CASE
        WHEN PAY>= 400 THEN 'A'
        WHEN PAY>= 300 THEN 'B'
        ELSE 'C'
    END AS PAY_GRADE
FROM PROFESSOR;

